.github/workflows/depoly.yml

ignore 처리된 properties 생성

---

.github/workflows/depoly.yml

#12 ap-northeast-2 를 직접 depoly에 정의 해줌

fix: aws-region 값을 받아오지 못하는 문제 수정

---

.github/workflows/depoly.yml

#3 #14 기존 존재하지 않았던 isntyet-deploy를 sim-deploy 버킷으로 변경

fix: 존재하지 않았던 버킷 이름 변경

---

deploy.sh

Reverts GreenStep99/Backend#16

Revert "줄바꿈(main 브랜치 머지시 자동배포 기능 테스트)"

---

deploy.sh

Reverts GreenStep99/Backend#17

Revert "Revert "줄바꿈(main 브랜치 머지시 자동배포 기능 테스트)""

---

deploy.sh

Reverts GreenStep99/Backend#18

Revert "Revert "Revert "줄바꿈(main 브랜치 머지시 자동배포 기능 테스트)"""

---

.github/workflows/depoly.yml

fix: 엑세스키와 시크릿키 경로 재정의

---

src/main/java/com/hanghae/greenstep/configuration/WebMvcConfiguration.java

fix: WebMvpConfig 파일에 http://54.180.30.74 허용 추가

---

src/main/java/com/hanghae/greenstep/configuration/WebMvcConfiguration.java

fix: WebMvpConfig 파일 http://54.180.30.74 -> http://54.180.30.74/ 수정

---

.github/workflows/depoly.yml

fix: properties 파일 생성 부분 삭제

---

.github/workflows/depoly.yml

Reverts GreenStep99/Backend#28 #25

Revert "fix: properties 파일 생성 부분 삭제"

---

src/main/java/com/hanghae/greenstep/configuration/WebMvcConfiguration.java

fix: WebMveConfig http://54.180.30.74:80/ 추가

---

src/main/java/com/hanghae/greenstep/configuration/WebMvcConfiguration.java

fix: 도메인 경로 맨 끝 /제거, http://54.180.30.74추가

---

src/main/java/com/hanghae/greenstep/configuration/WebMvcConfiguration.java
src/main/java/com/hanghae/greenstep/feed/Feed.java
src/main/java/com/hanghae/greenstep/jwt/TokenDto.java
src/main/java/com/hanghae/greenstep/member/MemberService.java

fix : 카카오 로그인 권한 설정

---

src/main/java/com/hanghae/greenstep/jwt/UserDetailsImpl.java
src/main/java/com/hanghae/greenstep/jwt/UserDetailsServiceImpl.java
src/main/java/com/hanghae/greenstep/member/MemberRepository.java

UserDetail의 loadByUsername의 Username이 고유값이 아니라 고유값인 Email로 대체

fix: 로그인 시 Response값 추가, UserDetail의 고유값 변경

---

src/main/java/com/hanghae/greenstep/member/MemberResponseDto.java
src/main/java/com/hanghae/greenstep/member/MemberService.java

feature: 유저 정보 조회기능 추가

---

src/main/java/com/hanghae/greenstep/configuration/WebMvcConfiguration.java
src/main/java/com/hanghae/greenstep/feed/Feed.java
src/main/java/com/hanghae/greenstep/jwt/TokenDto.java
src/main/java/com/hanghae/greenstep/member/MemberService.java

Reverts GreenStep99/Backend#32

Revert "fix : 카카오 로그인 권한 설정"

---

src/main/java/com/hanghae/greenstep/jwt/UserDetailsImpl.java
src/main/java/com/hanghae/greenstep/jwt/UserDetailsServiceImpl.java
src/main/java/com/hanghae/greenstep/member/MemberRepository.java

Reverts GreenStep99/Backend#33

Revert "fix: UserDetail의 고유값 변경"

---

src/main/java/com/hanghae/greenstep/admin/AdminController.java
src/main/java/com/hanghae/greenstep/admin/AdminService.java
src/main/java/com/hanghae/greenstep/admin/SubmitMissionResponseDto.java
src/main/java/com/hanghae/greenstep/submitMission/SubmitMission.java
src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionRepository.java

feat: SubmitMission 목록 조회 기능 추가

---

src/main/java/com/hanghae/greenstep/kakaoLogin/KakaoMemberInfoDto.java

fix: 가지고 오지 못하는 정보 제거

---

src/main/java/com/hanghae/greenstep/clap/ClapRepository.java
src/main/java/com/hanghae/greenstep/feed/FeedController.java
src/main/java/com/hanghae/greenstep/feed/FeedRepository.java
src/main/java/com/hanghae/greenstep/feed/FeedResponseDto.java
src/main/java/com/hanghae/greenstep/feed/FeedService.java

feat: 전체 feed 조회 기능 추가

---

src/main/java/com/hanghae/greenstep/clap/Clap.java
src/main/java/com/hanghae/greenstep/clap/ClapController.java
src/main/java/com/hanghae/greenstep/clap/ClapRepository.java
src/main/java/com/hanghae/greenstep/clap/ClapRequestDto.java
src/main/java/com/hanghae/greenstep/clap/ClapService.java
src/main/java/com/hanghae/greenstep/feed/Feed.java

feat: 박수를 호출 할때마다 증가 감소하는 기능 추가(+피드별 박수 개수 업데이트)

---

src/main/java/com/hanghae/greenstep/feed/FeedService.java

fix: hearByMe_isEdit -> clapByMe_isEdit로 변수 명 변경

---

src/main/java/com/hanghae/greenstep/clap/ClapController.java
src/main/java/com/hanghae/greenstep/clap/ClapRepository.java
src/main/java/com/hanghae/greenstep/clap/ClapService.java

refactor: 박수 기능 리펙토링

---

src/main/java/com/hanghae/greenstep/clap/ClapRepository.java
src/main/java/com/hanghae/greenstep/feed/FeedService.java

fix: clap repository 예약어 변경

---

src/main/java/com/hanghae/greenstep/configuration/SecurityConfiguration.java

fix: 원활한 api 테스트를 위한 시큐리티 전체 허용 임시 추가

---

src/main/java/com/hanghae/greenstep/feed/FeedController.java
src/main/java/com/hanghae/greenstep/feed/FeedRepository.java
src/main/java/com/hanghae/greenstep/feed/FeedService.java

fix: feed 전체 조회 무한스크롤 기능 추가

---

src/main/java/com/hanghae/greenstep/feed/FeedController.java
src/main/java/com/hanghae/greenstep/feed/FeedRepository.java
src/main/java/com/hanghae/greenstep/feed/FeedService.java

fix: 전체Feed 조회 무한 스크롤 예약어 문제 수정.(feedRepository 예약어 'in' 삭제)

---

src/main/java/com/hanghae/greenstep/feed/Feed.java
src/main/java/com/hanghae/greenstep/feed/FeedController.java
src/main/java/com/hanghae/greenstep/feed/FeedRepository.java
src/main/java/com/hanghae/greenstep/feed/FeedService.java

feat: feed 카테고리별 조회(무한 스크롤 기능 추가)

---

src/main/java/com/hanghae/greenstep/rank/RankController.java
src/main/java/com/hanghae/greenstep/rank/RankService.java
src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionRepository.java

feat: 미션 인증 완료 횟수 기준으로 내림차순으로 유저 정렬 기능 추가

---

src/main/java/com/hanghae/greenstep/clap/ClapService.java
src/main/java/com/hanghae/greenstep/exception/ErrorCode.java
src/main/java/com/hanghae/greenstep/feed/FeedService.java
src/main/java/com/hanghae/greenstep/shared/Check.java
src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionResponseDto.java

feature: feed 생성시 작성자 체크 로직 생성

---

src/main/java/com/hanghae/greenstep/admin/AdminController.java
src/main/java/com/hanghae/greenstep/admin/AdminService.java
src/main/java/com/hanghae/greenstep/submitMission/SubmitMission.java
src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionResponseDto.java

Param값을 Status로 받고 info를 @nullable을 달아줌으로서 수락과 거절을 중복코드 없이 한 메소드로 처리 #7

refactor: Status를 받아 중복 코드 제거

---

src/main/java/com/hanghae/greenstep/admin/AdminService.java
src/main/java/com/hanghae/greenstep/member/Member.java

feat: 미션 포인트 획득 기능 추가

---

src/main/java/com/hanghae/greenstep/admin/AdminService.java
src/main/java/com/hanghae/greenstep/admin/ApplicatonEventPublisher.java
src/main/java/com/hanghae/greenstep/feed/FeedController.java
src/main/java/com/hanghae/greenstep/feed/FeedRepository.java
src/main/java/com/hanghae/greenstep/feed/FeedResponseDto.java
src/main/java/com/hanghae/greenstep/feed/FeedService.java
src/main/java/com/hanghae/greenstep/missionStatus/MissionStatus.java
src/main/java/com/hanghae/greenstep/submitMission/MyMissionsDto.java
src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionController.java
src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionRepository.java
src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionResponseDto.java
src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionService.java

refactor: FeedService의 feedResponseDto 생성 중복 코드 분리

feat: profile 인증샷 목록 불러오기, 내 피드 목록 불러오기

---

src/main/java/com/hanghae/greenstep/member/MemberRepository.java
src/main/java/com/hanghae/greenstep/rank/RankController.java
src/main/java/com/hanghae/greenstep/rank/RankService.java

feat: 일일 포인트 랭킹, 주간 포인트 랭킹, 전체 포인트 랭킹 조회 추가

---

src/main/java/com/hanghae/greenstep/member/Member.java

fix: 총, 일간, 주간 미션포인트 default 값이 null 인 문제 수정.(0으로 수정)

---

src/main/java/com/hanghae/greenstep/admin/AdminService.java
src/main/java/com/hanghae/greenstep/kakaoLogin/KakaoLoginService.java
src/main/java/com/hanghae/greenstep/member/Member.java
src/main/java/com/hanghae/greenstep/member/MemberRequestDto.java

feat: 이메일 수신 동의 기능 추가

---

src/main/java/com/hanghae/greenstep/member/MemberRepository.java
src/main/java/com/hanghae/greenstep/rank/MemberRankResponseDto.java
src/main/java/com/hanghae/greenstep/rank/RankService.java
src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionRepository.java

fix: 모든 랭킹 상위 3명만 조회 + 리펙토링

---

src/main/java/com/hanghae/greenstep/member/MemberRepository.java
src/main/java/com/hanghae/greenstep/rank/RankController.java
src/main/java/com/hanghae/greenstep/rank/RankService.java
src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionRepository.java

fix: 사용안하는 랭킹 api 기능들 삭제

---

src/main/java/com/hanghae/greenstep/admin/AdminService.java
src/main/java/com/hanghae/greenstep/feed/FeedService.java
src/main/java/com/hanghae/greenstep/member/MemberService.java
src/main/java/com/hanghae/greenstep/rank/RankService.java
src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionService.java

refactor: @transactional(read"Only = true) 읽기 전용 트랜잭션 사용을 통한 조회 속도 최적화

---

src/main/java/com/hanghae/greenstep/admin/AdminController.java
src/main/java/com/hanghae/greenstep/admin/AdminLoginRequestDto.java
src/main/java/com/hanghae/greenstep/admin/AdminService.java
src/main/java/com/hanghae/greenstep/feed/FeedController.java
src/main/java/com/hanghae/greenstep/feed/FeedResponseDto.java
src/main/java/com/hanghae/greenstep/member/Member.java
src/main/java/com/hanghae/greenstep/member/MemberRepository.java
src/main/java/com/hanghae/greenstep/member/MemberService.java
src/main/java/com/hanghae/greenstep/shared/Timestamped.java
src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionService.java

관리자 회원가입 기능 여부가 불투명하여 임시로 빼놓은 비밀번호 검증로직 추가

fix: admin password 확인 로직 추가

---

src/main/java/com/hanghae/greenstep/configuration/WebMvcConfiguration.java

fix: cors https 클라우드프론트, 로드밸런서 주소 추가

---

src/main/java/com/hanghae/greenstep/shared/mail/EmailService.java
src/main/java/com/hanghae/greenstep/shared/mail/EmailUtilImpl.java
src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionRepository.java

query에 머지 후 누락된 @Param과 쿼리문 오류 수정

fix: 검증시 생기는 리포지토리 쿼리 오류 수정

---

src/main/java/com/hanghae/greenstep/member/Member.java

fix: weeklyMissionPoint 칼럼 삭제

---

src/main/java/com/hanghae/greenstep/admin/AdminService.java
src/main/java/com/hanghae/greenstep/clap/ClapService.java
src/main/java/com/hanghae/greenstep/exception/ErrorCode.java
src/main/java/com/hanghae/greenstep/member/Member.java
src/main/java/com/hanghae/greenstep/notice/EmitterRepository.java
src/main/java/com/hanghae/greenstep/notice/EmitterRepositoryImpl.java
src/main/java/com/hanghae/greenstep/notice/Notification.java
src/main/java/com/hanghae/greenstep/notice/NotificationController.java
src/main/java/com/hanghae/greenstep/notice/NotificationCountDto.java
src/main/java/com/hanghae/greenstep/notice/NotificationRepository.java
src/main/java/com/hanghae/greenstep/notice/NotificationResponseDto.java
src/main/java/com/hanghae/greenstep/notice/NotificationService.java
src/main/java/com/hanghae/greenstep/shared/notice/NotificationContent.java
src/main/java/com/hanghae/greenstep/shared/notice/NotificationType.java
src/main/java/com/hanghae/greenstep/shared/notice/RelatedURL.java
src/test/java/com/hanghae/greenstep/notice/EmitterRepositoryImplTest.java
src/test/java/com/hanghae/greenstep/notice/embeddable/NotificationContentTest.java
src/test/java/com/hanghae/greenstep/notice/embeddable/RelatedURLTest.java

feat: [SSE] 실시간 알림 기능 구현

---

src/main/java/com/hanghae/greenstep/clap/ClapService.java

fix: 알림을 받는 멤버가 박수 받는 멤버가 아닌 박수를 주는 멤버인 것을 확인. 박수 받는 멤버를 알림을 받는 멤버로 변경

---

src/test/java/com/hanghae/greenstep/notice/EmitterRepositoryImplTest.java

fix: 코드 수정으로 인한 이전에 사용한 테스트 코드 파일 주석처리

---

src/main/java/com/hanghae/greenstep/admin/AdminService.java
src/main/java/com/hanghae/greenstep/clap/ClapService.java

fix: 프론트 측 eventresource 미구현으로 인한 코드 에러들 임시 주석처리

---

src/main/java/com/hanghae/greenstep/notice/Notification.java

fix: 빌드오류 @EqualsAndHashCode(of = "id") 주석처리

---

src/main/java/com/hanghae/greenstep/admin/AdminController.java
src/main/java/com/hanghae/greenstep/admin/AdminService.java
src/main/java/com/hanghae/greenstep/clap/ClapController.java
src/main/java/com/hanghae/greenstep/clap/ClapService.java
src/main/java/com/hanghae/greenstep/feed/FeedController.java
src/main/java/com/hanghae/greenstep/feed/FeedService.java
src/main/java/com/hanghae/greenstep/image/ImageController.java
src/main/java/com/hanghae/greenstep/kakaoLogin/KakaoSocialController.java
src/main/java/com/hanghae/greenstep/kakaoLogin/KakaoSocialService.java
src/main/java/com/hanghae/greenstep/kakaoShare/KakaoShareController.java
src/main/java/com/hanghae/greenstep/kakaoShare/KakaoShareService.java
src/main/java/com/hanghae/greenstep/member/MemberController.java
src/main/java/com/hanghae/greenstep/member/MemberService.java
src/main/java/com/hanghae/greenstep/mission/MissionController.java
src/main/java/com/hanghae/greenstep/mission/MissionService.java
src/main/java/com/hanghae/greenstep/notice/NotificationService.java
src/main/java/com/hanghae/greenstep/rank/RankController.java
src/main/java/com/hanghae/greenstep/rank/RankService.java
src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionController.java
src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionService.java

refactor: 피드백에 따른 Service, Controller 각각 리턴값 정리

---

src/main/java/com/hanghae/greenstep/feed/Feed.java
src/main/java/com/hanghae/greenstep/feed/FeedRepository.java
src/main/java/com/hanghae/greenstep/feed/FeedService.java
src/main/java/com/hanghae/greenstep/submitMission/SubmitMission.java
src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionService.java

#150  인증샷이 숨겨질 시 해당 인증샷의 피드도 숨겨지도록 기능 추가

feat: 인증샷 숨기기 시, feed도 숨겨지는 기능 추가

---

src/main/java/com/hanghae/greenstep/feed/FeedRepository.java
src/main/java/com/hanghae/greenstep/feed/FeedService.java

원인 JPA  = findByIdLessThanAndOnHideAndTagOrderByIdDesc 의 And 가 LessThan 앞에 있어서 생긴 오류

fix : 숨기지 않은 피드가 안보이는 버그 fix

---

src/main/java/com/hanghae/greenstep/admin/AdminService.java
src/main/java/com/hanghae/greenstep/exception/ErrorCode.java
src/main/java/com/hanghae/greenstep/kakaoAPI/KakaoSocialService.java
src/main/java/com/hanghae/greenstep/member/MemberService.java
src/main/java/com/hanghae/greenstep/mission/Dto/MissionResponseDto.java
src/main/java/com/hanghae/greenstep/mission/Mission.java
src/main/java/com/hanghae/greenstep/mission/MissionService.java

fix: nickname, name값의 정규식 필터 추가 

---

deploy.sh

fix: 배포 자동화 적용시 nohup.out 파일 생성되게 수정

---

deploy.sh

fix: 서버 실행 안되는 문제 수정

---

deploy.sh

Reverts GreenStep99/Backend#171
#3

Revert "fix: 서버 실행 안되는 문제 수정"

---

deploy.sh

Reverts GreenStep99/Backend#171
#3

Revert "fix: 배포 자동화 적용시 nohup.out 파일 생성되게 수정"

---

src/main/java/com/hanghae/greenstep/member/MemberService.java

fix: 정규식 오류 수정

---

src/main/resources/logback.xml

해당 사이트 참조 https://harrydony.tistory.com/245
#3

fix: 에러로그만 확인기능 추가

---

src/main/java/com/hanghae/greenstep/admin/AdminService.java

fix: 미션 인가시 알림 재추가

---

src/main/java/com/hanghae/greenstep/admin/AdminService.java
src/main/java/com/hanghae/greenstep/clap/ClapService.java
src/main/java/com/hanghae/greenstep/exception/ErrorCode.java
src/main/java/com/hanghae/greenstep/notice/Dto/NotificationDto.java
src/main/java/com/hanghae/greenstep/notice/Dto/NotificationRequestDto.java
src/main/java/com/hanghae/greenstep/notice/Notification.java
src/main/java/com/hanghae/greenstep/notice/NotificationService.java
src/main/java/com/hanghae/greenstep/notice/RelatedIMGURL.java

fix: 알림 시 이미지 url 도 보낼수 있게 추가

---

src/main/java/com/hanghae/greenstep/clap/ClapService.java
src/main/java/com/hanghae/greenstep/notice/Dto/NotificationDto.java
src/main/java/com/hanghae/greenstep/notice/Notification.java

feat: 알림 생성 시간 표시되게 추가

---

src/main/java/com/hanghae/greenstep/admin/AdminService.java

feat: 미션인증 거부시 알림 전송 추가

---

src/main/java/com/hanghae/greenstep/configuration/SecurityConfiguration.java
src/main/java/com/hanghae/greenstep/notice/NotificationController.java
src/main/java/com/hanghae/greenstep/notice/NotificationService.java

feat: 알림 선택 삭제 기능 추가

---

src/main/java/com/hanghae/greenstep/configuration/SecurityConfiguration.java

fix: 중복로그인 테스트 코드 머지된거 삭제
